fix: issues with the given samples
kptdev/kpt pull request #3415
Opened 2022-07-25 23:02 UTC by Shabirmean

- Running `go mod init` without. a module name throws an error
- The `kubeObject.IsGVK` function has three arguments `group, version, kind string`

2022-07-25 23:45 UTC, yuwenma commented
Thank you @Shabirmean, one minor comment.

2022-07-26 02:29 UTC, Shabirmean commented
> Thank you @Shabirmean, one minor comment.

Thank you for the quick review @yuwenma. Sorry, but I am not seeing any comments. Did you want me to look into something?

2022-07-26 05:15 UTC, yuwenma requested changes

2022-07-26 05:18 UTC, yuwenma commented on site/book/05-developing-functions/02-developing-in-Go.md
> +go mod init kpt-fn/set-annotation
did you run ln 32 to `cd` into the ${FUNCTION_NAME}

2022-07-26 14:17 UTC, Shabirmean commented on site/book/05-developing-functions/02-developing-in-Go.md
> +go mod init kpt-fn/set-annotation
I've tried both ways:
- First `cd ${FUNCTION_NAME}` and then do `go mod init`
- First `go mod init` 

In both cases I get the error
```
go: cannot determine module path for source directory /tmp/kpt/set-annotation (outside GOPATH, module path must be specified)

Example usage:
	'go mod init example.com/m' to initialize a v0 or v1 module
	'go mod init example.com/m/v2' to initialize a v2 module

Run 'go help mod init' for more information.
```

Sorry, I am quite new to Go and not completely sure if I am missing some specific setup in my environment.

2025-08-15 09:10 UTC, closed without merging